#! configuration/config.yaml
region: "us-east-1"
cluster_settings:
  name: "xre-sports-app"
  description: "xre-sport-app demo"
  node_type: "db.t4g.small"
  acl_name: "open-access"
  num_shards: 2
  num_replicas_per_shard: 1
  subnet_group_name: "xre-sports-subnet-group"
  subnet_ids:
    - "subnet-023d860bce456eee8"
    - "subnet-021a75b619ec30956"
    - "subnet-0080dd9162d64e9dd"
